import { HashMap } from "./hashMap.js";
const myHashMap = new HashMap();
myHashMap.set(`Uria`, 35);
console.log(myHashMap);
myHashMap.set(`Irina`, 32);
console.log(myHashMap);
myHashMap.set(`asdfgqwerty`, 32);
console.log(myHashMap);
myHashMap.set(`Uria`, 35);
console.log(myHashMap);
myHashMap.set(`Irina`, 32);
console.log(myHashMap.memory);
